//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailorShopWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeasurement
    {
        public int MesurementID { get; set; }
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> CloathID { get; set; }
        public Nullable<double> Neak { get; set; }
        public Nullable<double> Chest { get; set; }
        public Nullable<double> Waist { get; set; }
        public Nullable<double> Seat { get; set; }
        public Nullable<double> ShirtLength { get; set; }
        public Nullable<double> HalfShoulder { get; set; }
        public Nullable<double> ShoulderWidth { get; set; }
        public Nullable<double> ArmLength { get; set; }
        public Nullable<double> biceps { get; set; }
        public Nullable<double> wrist { get; set; }
        public Nullable<double> lnseam { get; set; }
        public Nullable<double> Hip { get; set; }
        public Nullable<double> CoatSleeveLength { get; set; }
        public Nullable<double> SleeveLengthForSuit { get; set; }
        public Nullable<double> JacketLength { get; set; }
        public Nullable<double> Thigh { get; set; }
        public Nullable<double> AboveKnee { get; set; }
        public Nullable<double> BelowKnee { get; set; }
        public Nullable<double> Ankle { get; set; }
        public Nullable<double> CrotchToKnee { get; set; }
        public Nullable<double> KneeToKalf { get; set; }
        public Nullable<double> CalfToAnkle { get; set; }
        public Nullable<double> WaistToAnkle { get; set; }
    }
}
