//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailorShopWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatternInfo
    {
        public int OrderID { get; set; }
        public int CloathID { get; set; }
        public int MesurementID { get; set; }
        public Nullable<int> Total_Poket { get; set; }
        public string Poket_Note { get; set; }
        public string Sleeve { get; set; }
        public string Sleeve_Note { get; set; }
        public string Collar_Note { get; set; }
        public string Other_Note { get; set; }
        public string Cloth_PhotoPattern { get; set; }
    }
}
