//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailorShopWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentStatu
    {
        public int PaymentStatusID { get; set; }
        public string PaymentStatusName { get; set; }
    }
}
