//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailorShopWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStore
    {
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public string StoreMobileNo { get; set; }
        public string StoreAddress { get; set; }
        public string StoreEmailId { get; set; }
        public Nullable<int> StoreStatus { get; set; }
    }
}
